url: "https://www.opensleigh.net" 
plugins:
  - jekyll-sitemap
  
google_analytics: G-V6KPT320HR
theme: jekyll-theme-architect

title: OpenSleigh
tagline: Yet another Saga management library for .NET Core.
description: OpenSleigh - Yet another Saga management library for .NET Core.

twitter:
  username: DavideGuida82
  card: summary

author:
  twitter: DavideGuida82

github:
  repository_url: https://github.com/mizrael/OpenSleigh
  repository_name: OpenSleigh
  owner_url: https://www.davideguida.com
  owner_name: David Guida

nugets:
  Core: https://www.nuget.org/packages/OpenSleigh.Core/
  In-Memory: https://www.nuget.org/packages/OpenSleigh.Persistence.InMemory/
  MongoDB: https://www.nuget.org/packages/OpenSleigh.Persistence.Mongo/
  MSSQL: https://www.nuget.org/packages/OpenSleigh.Persistence.SQL/
  Azure Service Bus: https://www.nuget.org/packages/OpenSleigh.Transport.AzureServiceBus/
  RabbitMQ: https://www.nuget.org/packages/OpenSleigh.Transport.RabbitMQ/
  CosmosDB: https://www.nuget.org/packages/OpenSleigh.Persistence.Cosmos/

sidebar:
  Home: /
  How-to: /how-to
  Samples: /samples
